/* eslint-disable no-new */
export const vsIOTTransacciones = {
  BUSCARCLIENTE: "BuscarCliente",
  ENVIAREMAILS: "EnviarEmails",
  BUSCARNOMBRE: "BuscarNombre",
  BUSCARAPELLIDO: "BuscarApellido",
  BUSCARREGION: "BuscarRegion",
  OBTENERINFORMACIONCLIENTE: "ObtenerInformacionCliente",
  CARGARMENUAPP: "CargarMenuAPP",
  CARGARAPLICACIONESROL: "CargarAplicacionesRol",
  OBTENERLSTAPLICACIONES: "ObtenerAplicaciones",
  OBTENERDATOSCIA: "ObtenerDatosCia",
  OBTENERLSTMODULOS: "ObtenerModulos",
  OBTENERAPLICACIONESMODULOSADDDEL: "ObtenerAplicacionesModulosAddDel",
  OBTENERAPLICACIONESROLESADDDEL: "ObtenerAplicacionesRolesAddDel",
  OBTENERMODULOSSUBMODULOSADDDEL: "ObtenerModulosSubModulosAddDel",
  OBTENERMODULOSROLESADDDEL: "ObtenerModulosRolesAddDel",
  OBTENERSUBMODULOSROLESADDDEL: "ObtenerSubModulosRolesAddDel",
  OBTENERSUBMODULOSFORMULARIOSADDDEL: "ObtenerSubModulosFormulariosAddDel",
  OBTENERFORMULARIOSROLESADDDEL: "ObtenerFormulariosRolesAddDel",
  OBTENERFORMULARIOSTRANSACCIONESDDDEL: "ObtenerFormulariosTransaccionesAddDel",
  OBTENERTRANSACCIONESROLESADDDEL: "ObtenerTransaccionesRolesAddDel",
  OBTENERSUBMODULOS: "ObtenerSubModulos",
  OBTENERTRANSACCIONESAPP: "ObtenerTransaccionesApp",
  OBTENERESTADOSTRANSACCIONESAPP: "ObtenerEstadosTransaccionesApp",
  OBTENERFORMULARIOS: "ObtenerFormularios",
  OBTENERUSUARIOS: "ObtenerUsuarios",
  OBTENERLSTSUCURSALESAGENCIAS: "ObtenerSucursalesAgencias",
  OBTENERTIPOSDATOSUSUARIOS: "ObtenerTiposDatosUsuarios", //Optiene tipos de datos usuario como Estados,Tipo Documento, Tipo Direcciones,Telefonos etc
  OBTENERLSTROLES: "ObtenerRoles",
  OBTENERLSTSENSORES: "ObtenerSensores",
  OBTENERLSTMARCAVEHICULOS: "ObtenerMarcaVehiculos",
  OBTENERLSTCATEGORIAPRODUCTOS: "ObtenerCategoriaProductos",
  ADMONFRMMARCASVHS: "AdmonFrmMarcasVHS",
  ADMONFRMPUC: "AdmonFrmPUC",
  ADMONFRMBANCOS: "AdmonFrmBancos",
  OBTENERLSTLINEAPRODUCTOS: "ObtenerLineaProductos",
  ADMONFRMMENSAJESCLIENTE: "AdmonFrmMensajesClientes",
  CARCARINLISTANEGOCIACIONES: "CarCaringListaNegociaciones",
  CARGARPARAMETROSCONTABILIDAD: "CargarParametrosContabilidad",
  CARCARINPROCESARTECNICOS: "CarCaringProcesarTecnicos",
  // eslint-disable-next-line prettier/pretCarCaringListaNegociacionestier
  CARCARINOBTENERCOMPONENTESNEGOCIACION:
    "CarCaringObtenerComponentesNegociacion",
  BUSCARPAISES: "BuscarPais",
  BUSCARDEPTOS: "BuscarDepto",
  BUSCARCIUDADES: "BuscarCiudad",
  LOGINUSER: "LoginUser",
  LOGOUTUSER: "LogoutUser",
  CAMBIARUSERPASSWORD: "CambiarUserPassWord"
};
